// jtag_axi_sys_mm_interconnect_0.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.0 614

`timescale 1 ps / 1 ps
module jtag_axi_sys_mm_interconnect_0 (
		output wire [7:0]  axi_bridge_0_s0_awid,                               //                              axi_bridge_0_s0.awid
		output wire [31:0] axi_bridge_0_s0_awaddr,                             //                                             .awaddr
		output wire [7:0]  axi_bridge_0_s0_awlen,                              //                                             .awlen
		output wire [2:0]  axi_bridge_0_s0_awsize,                             //                                             .awsize
		output wire [1:0]  axi_bridge_0_s0_awburst,                            //                                             .awburst
		output wire [0:0]  axi_bridge_0_s0_awlock,                             //                                             .awlock
		output wire [3:0]  axi_bridge_0_s0_awcache,                            //                                             .awcache
		output wire [2:0]  axi_bridge_0_s0_awprot,                             //                                             .awprot
		output wire [3:0]  axi_bridge_0_s0_awqos,                              //                                             .awqos
		output wire [3:0]  axi_bridge_0_s0_awregion,                           //                                             .awregion
		output wire        axi_bridge_0_s0_awvalid,                            //                                             .awvalid
		input  wire        axi_bridge_0_s0_awready,                            //                                             .awready
		output wire [31:0] axi_bridge_0_s0_wdata,                              //                                             .wdata
		output wire [3:0]  axi_bridge_0_s0_wstrb,                              //                                             .wstrb
		output wire        axi_bridge_0_s0_wlast,                              //                                             .wlast
		output wire        axi_bridge_0_s0_wvalid,                             //                                             .wvalid
		input  wire        axi_bridge_0_s0_wready,                             //                                             .wready
		input  wire [7:0]  axi_bridge_0_s0_bid,                                //                                             .bid
		input  wire [1:0]  axi_bridge_0_s0_bresp,                              //                                             .bresp
		input  wire        axi_bridge_0_s0_bvalid,                             //                                             .bvalid
		output wire        axi_bridge_0_s0_bready,                             //                                             .bready
		output wire [7:0]  axi_bridge_0_s0_arid,                               //                                             .arid
		output wire [31:0] axi_bridge_0_s0_araddr,                             //                                             .araddr
		output wire [7:0]  axi_bridge_0_s0_arlen,                              //                                             .arlen
		output wire [2:0]  axi_bridge_0_s0_arsize,                             //                                             .arsize
		output wire [1:0]  axi_bridge_0_s0_arburst,                            //                                             .arburst
		output wire [0:0]  axi_bridge_0_s0_arlock,                             //                                             .arlock
		output wire [3:0]  axi_bridge_0_s0_arcache,                            //                                             .arcache
		output wire [2:0]  axi_bridge_0_s0_arprot,                             //                                             .arprot
		output wire [3:0]  axi_bridge_0_s0_arqos,                              //                                             .arqos
		output wire [3:0]  axi_bridge_0_s0_arregion,                           //                                             .arregion
		output wire        axi_bridge_0_s0_arvalid,                            //                                             .arvalid
		input  wire        axi_bridge_0_s0_arready,                            //                                             .arready
		input  wire [7:0]  axi_bridge_0_s0_rid,                                //                                             .rid
		input  wire [31:0] axi_bridge_0_s0_rdata,                              //                                             .rdata
		input  wire [1:0]  axi_bridge_0_s0_rresp,                              //                                             .rresp
		input  wire        axi_bridge_0_s0_rlast,                              //                                             .rlast
		input  wire        axi_bridge_0_s0_rvalid,                             //                                             .rvalid
		output wire        axi_bridge_0_s0_rready,                             //                                             .rready
		input  wire        clk_0_clk_clk,                                      //                                    clk_0_clk.clk
		input  wire        axi_bridge_0_clk_reset_reset_bridge_in_reset_reset, // axi_bridge_0_clk_reset_reset_bridge_in_reset.reset
		input  wire        master_0_clk_reset_reset_bridge_in_reset_reset,     //     master_0_clk_reset_reset_bridge_in_reset.reset
		input  wire [31:0] master_0_master_address,                            //                              master_0_master.address
		output wire        master_0_master_waitrequest,                        //                                             .waitrequest
		input  wire [3:0]  master_0_master_byteenable,                         //                                             .byteenable
		input  wire        master_0_master_read,                               //                                             .read
		output wire [31:0] master_0_master_readdata,                           //                                             .readdata
		output wire        master_0_master_readdatavalid,                      //                                             .readdatavalid
		input  wire        master_0_master_write,                              //                                             .write
		input  wire [31:0] master_0_master_writedata                           //                                             .writedata
	);

	wire          master_0_master_translator_avalon_universal_master_0_waitrequest;   // master_0_master_agent:av_waitrequest -> master_0_master_translator:uav_waitrequest
	wire   [31:0] master_0_master_translator_avalon_universal_master_0_readdata;      // master_0_master_agent:av_readdata -> master_0_master_translator:uav_readdata
	wire          master_0_master_translator_avalon_universal_master_0_debugaccess;   // master_0_master_translator:uav_debugaccess -> master_0_master_agent:av_debugaccess
	wire   [31:0] master_0_master_translator_avalon_universal_master_0_address;       // master_0_master_translator:uav_address -> master_0_master_agent:av_address
	wire          master_0_master_translator_avalon_universal_master_0_read;          // master_0_master_translator:uav_read -> master_0_master_agent:av_read
	wire    [3:0] master_0_master_translator_avalon_universal_master_0_byteenable;    // master_0_master_translator:uav_byteenable -> master_0_master_agent:av_byteenable
	wire          master_0_master_translator_avalon_universal_master_0_readdatavalid; // master_0_master_agent:av_readdatavalid -> master_0_master_translator:uav_readdatavalid
	wire          master_0_master_translator_avalon_universal_master_0_lock;          // master_0_master_translator:uav_lock -> master_0_master_agent:av_lock
	wire          master_0_master_translator_avalon_universal_master_0_write;         // master_0_master_translator:uav_write -> master_0_master_agent:av_write
	wire   [31:0] master_0_master_translator_avalon_universal_master_0_writedata;     // master_0_master_translator:uav_writedata -> master_0_master_agent:av_writedata
	wire    [2:0] master_0_master_translator_avalon_universal_master_0_burstcount;    // master_0_master_translator:uav_burstcount -> master_0_master_agent:av_burstcount
	wire    [0:0] axi_bridge_0_s0_agent_altera_axi_master_ruser;                      // axi_bridge_0_s0_translator:s0_ruser -> axi_bridge_0_s0_agent:ruser
	wire    [0:0] axi_bridge_0_s0_agent_altera_axi_master_wuser;                      // axi_bridge_0_s0_agent:wuser -> axi_bridge_0_s0_translator:s0_wuser
	wire    [1:0] axi_bridge_0_s0_agent_altera_axi_master_awburst;                    // axi_bridge_0_s0_agent:awburst -> axi_bridge_0_s0_translator:s0_awburst
	wire    [3:0] axi_bridge_0_s0_agent_altera_axi_master_arregion;                   // axi_bridge_0_s0_agent:arregion -> axi_bridge_0_s0_translator:s0_arregion
	wire    [0:0] axi_bridge_0_s0_agent_altera_axi_master_awuser;                     // axi_bridge_0_s0_agent:awuser -> axi_bridge_0_s0_translator:s0_awuser
	wire    [7:0] axi_bridge_0_s0_agent_altera_axi_master_arlen;                      // axi_bridge_0_s0_agent:arlen -> axi_bridge_0_s0_translator:s0_arlen
	wire    [3:0] axi_bridge_0_s0_agent_altera_axi_master_arqos;                      // axi_bridge_0_s0_agent:arqos -> axi_bridge_0_s0_translator:s0_arqos
	wire    [3:0] axi_bridge_0_s0_agent_altera_axi_master_wstrb;                      // axi_bridge_0_s0_agent:wstrb -> axi_bridge_0_s0_translator:s0_wstrb
	wire          axi_bridge_0_s0_agent_altera_axi_master_wready;                     // axi_bridge_0_s0_translator:s0_wready -> axi_bridge_0_s0_agent:wready
	wire    [0:0] axi_bridge_0_s0_agent_altera_axi_master_rid;                        // axi_bridge_0_s0_translator:s0_rid -> axi_bridge_0_s0_agent:rid
	wire          axi_bridge_0_s0_agent_altera_axi_master_rready;                     // axi_bridge_0_s0_agent:rready -> axi_bridge_0_s0_translator:s0_rready
	wire    [7:0] axi_bridge_0_s0_agent_altera_axi_master_awlen;                      // axi_bridge_0_s0_agent:awlen -> axi_bridge_0_s0_translator:s0_awlen
	wire    [3:0] axi_bridge_0_s0_agent_altera_axi_master_awqos;                      // axi_bridge_0_s0_agent:awqos -> axi_bridge_0_s0_translator:s0_awqos
	wire    [3:0] axi_bridge_0_s0_agent_altera_axi_master_arcache;                    // axi_bridge_0_s0_agent:arcache -> axi_bridge_0_s0_translator:s0_arcache
	wire          axi_bridge_0_s0_agent_altera_axi_master_wvalid;                     // axi_bridge_0_s0_agent:wvalid -> axi_bridge_0_s0_translator:s0_wvalid
	wire   [31:0] axi_bridge_0_s0_agent_altera_axi_master_araddr;                     // axi_bridge_0_s0_agent:araddr -> axi_bridge_0_s0_translator:s0_araddr
	wire    [2:0] axi_bridge_0_s0_agent_altera_axi_master_arprot;                     // axi_bridge_0_s0_agent:arprot -> axi_bridge_0_s0_translator:s0_arprot
	wire    [2:0] axi_bridge_0_s0_agent_altera_axi_master_awprot;                     // axi_bridge_0_s0_agent:awprot -> axi_bridge_0_s0_translator:s0_awprot
	wire   [31:0] axi_bridge_0_s0_agent_altera_axi_master_wdata;                      // axi_bridge_0_s0_agent:wdata -> axi_bridge_0_s0_translator:s0_wdata
	wire          axi_bridge_0_s0_agent_altera_axi_master_arvalid;                    // axi_bridge_0_s0_agent:arvalid -> axi_bridge_0_s0_translator:s0_arvalid
	wire    [3:0] axi_bridge_0_s0_agent_altera_axi_master_awcache;                    // axi_bridge_0_s0_agent:awcache -> axi_bridge_0_s0_translator:s0_awcache
	wire    [0:0] axi_bridge_0_s0_agent_altera_axi_master_arid;                       // axi_bridge_0_s0_agent:arid -> axi_bridge_0_s0_translator:s0_arid
	wire    [0:0] axi_bridge_0_s0_agent_altera_axi_master_arlock;                     // axi_bridge_0_s0_agent:arlock -> axi_bridge_0_s0_translator:s0_arlock
	wire    [0:0] axi_bridge_0_s0_agent_altera_axi_master_awlock;                     // axi_bridge_0_s0_agent:awlock -> axi_bridge_0_s0_translator:s0_awlock
	wire   [31:0] axi_bridge_0_s0_agent_altera_axi_master_awaddr;                     // axi_bridge_0_s0_agent:awaddr -> axi_bridge_0_s0_translator:s0_awaddr
	wire    [1:0] axi_bridge_0_s0_agent_altera_axi_master_bresp;                      // axi_bridge_0_s0_translator:s0_bresp -> axi_bridge_0_s0_agent:bresp
	wire          axi_bridge_0_s0_agent_altera_axi_master_arready;                    // axi_bridge_0_s0_translator:s0_arready -> axi_bridge_0_s0_agent:arready
	wire   [31:0] axi_bridge_0_s0_agent_altera_axi_master_rdata;                      // axi_bridge_0_s0_translator:s0_rdata -> axi_bridge_0_s0_agent:rdata
	wire          axi_bridge_0_s0_agent_altera_axi_master_awready;                    // axi_bridge_0_s0_translator:s0_awready -> axi_bridge_0_s0_agent:awready
	wire    [1:0] axi_bridge_0_s0_agent_altera_axi_master_arburst;                    // axi_bridge_0_s0_agent:arburst -> axi_bridge_0_s0_translator:s0_arburst
	wire    [2:0] axi_bridge_0_s0_agent_altera_axi_master_arsize;                     // axi_bridge_0_s0_agent:arsize -> axi_bridge_0_s0_translator:s0_arsize
	wire          axi_bridge_0_s0_agent_altera_axi_master_bready;                     // axi_bridge_0_s0_agent:bready -> axi_bridge_0_s0_translator:s0_bready
	wire          axi_bridge_0_s0_agent_altera_axi_master_rlast;                      // axi_bridge_0_s0_translator:s0_rlast -> axi_bridge_0_s0_agent:rlast
	wire          axi_bridge_0_s0_agent_altera_axi_master_wlast;                      // axi_bridge_0_s0_agent:wlast -> axi_bridge_0_s0_translator:s0_wlast
	wire    [3:0] axi_bridge_0_s0_agent_altera_axi_master_awregion;                   // axi_bridge_0_s0_agent:awregion -> axi_bridge_0_s0_translator:s0_awregion
	wire    [0:0] axi_bridge_0_s0_agent_altera_axi_master_buser;                      // axi_bridge_0_s0_translator:s0_buser -> axi_bridge_0_s0_agent:buser
	wire    [1:0] axi_bridge_0_s0_agent_altera_axi_master_rresp;                      // axi_bridge_0_s0_translator:s0_rresp -> axi_bridge_0_s0_agent:rresp
	wire    [0:0] axi_bridge_0_s0_agent_altera_axi_master_awid;                       // axi_bridge_0_s0_agent:awid -> axi_bridge_0_s0_translator:s0_awid
	wire    [0:0] axi_bridge_0_s0_agent_altera_axi_master_bid;                        // axi_bridge_0_s0_translator:s0_bid -> axi_bridge_0_s0_agent:bid
	wire          axi_bridge_0_s0_agent_altera_axi_master_bvalid;                     // axi_bridge_0_s0_translator:s0_bvalid -> axi_bridge_0_s0_agent:bvalid
	wire    [2:0] axi_bridge_0_s0_agent_altera_axi_master_awsize;                     // axi_bridge_0_s0_agent:awsize -> axi_bridge_0_s0_translator:s0_awsize
	wire          axi_bridge_0_s0_agent_altera_axi_master_awvalid;                    // axi_bridge_0_s0_agent:awvalid -> axi_bridge_0_s0_translator:s0_awvalid
	wire    [0:0] axi_bridge_0_s0_agent_altera_axi_master_aruser;                     // axi_bridge_0_s0_agent:aruser -> axi_bridge_0_s0_translator:s0_aruser
	wire          axi_bridge_0_s0_agent_altera_axi_master_rvalid;                     // axi_bridge_0_s0_translator:s0_rvalid -> axi_bridge_0_s0_agent:rvalid
	wire          cmd_mux_src_valid;                                                  // cmd_mux:src_valid -> axi_bridge_0_s0_agent:write_cp_valid
	wire  [118:0] cmd_mux_src_data;                                                   // cmd_mux:src_data -> axi_bridge_0_s0_agent:write_cp_data
	wire          cmd_mux_src_ready;                                                  // axi_bridge_0_s0_agent:write_cp_ready -> cmd_mux:src_ready
	wire    [1:0] cmd_mux_src_channel;                                                // cmd_mux:src_channel -> axi_bridge_0_s0_agent:write_cp_channel
	wire          cmd_mux_src_startofpacket;                                          // cmd_mux:src_startofpacket -> axi_bridge_0_s0_agent:write_cp_startofpacket
	wire          cmd_mux_src_endofpacket;                                            // cmd_mux:src_endofpacket -> axi_bridge_0_s0_agent:write_cp_endofpacket
	wire          cmd_mux_001_src_valid;                                              // cmd_mux_001:src_valid -> axi_bridge_0_s0_agent:read_cp_valid
	wire  [118:0] cmd_mux_001_src_data;                                               // cmd_mux_001:src_data -> axi_bridge_0_s0_agent:read_cp_data
	wire          cmd_mux_001_src_ready;                                              // axi_bridge_0_s0_agent:read_cp_ready -> cmd_mux_001:src_ready
	wire    [1:0] cmd_mux_001_src_channel;                                            // cmd_mux_001:src_channel -> axi_bridge_0_s0_agent:read_cp_channel
	wire          cmd_mux_001_src_startofpacket;                                      // cmd_mux_001:src_startofpacket -> axi_bridge_0_s0_agent:read_cp_startofpacket
	wire          cmd_mux_001_src_endofpacket;                                        // cmd_mux_001:src_endofpacket -> axi_bridge_0_s0_agent:read_cp_endofpacket
	wire          master_0_master_agent_cp_valid;                                     // master_0_master_agent:cp_valid -> router:sink_valid
	wire  [118:0] master_0_master_agent_cp_data;                                      // master_0_master_agent:cp_data -> router:sink_data
	wire          master_0_master_agent_cp_ready;                                     // router:sink_ready -> master_0_master_agent:cp_ready
	wire          master_0_master_agent_cp_startofpacket;                             // master_0_master_agent:cp_startofpacket -> router:sink_startofpacket
	wire          master_0_master_agent_cp_endofpacket;                               // master_0_master_agent:cp_endofpacket -> router:sink_endofpacket
	wire          axi_bridge_0_s0_agent_write_rp_valid;                               // axi_bridge_0_s0_agent:write_rp_valid -> router_001:sink_valid
	wire  [118:0] axi_bridge_0_s0_agent_write_rp_data;                                // axi_bridge_0_s0_agent:write_rp_data -> router_001:sink_data
	wire          axi_bridge_0_s0_agent_write_rp_ready;                               // router_001:sink_ready -> axi_bridge_0_s0_agent:write_rp_ready
	wire          axi_bridge_0_s0_agent_write_rp_startofpacket;                       // axi_bridge_0_s0_agent:write_rp_startofpacket -> router_001:sink_startofpacket
	wire          axi_bridge_0_s0_agent_write_rp_endofpacket;                         // axi_bridge_0_s0_agent:write_rp_endofpacket -> router_001:sink_endofpacket
	wire          router_001_src_valid;                                               // router_001:src_valid -> rsp_demux:sink_valid
	wire  [118:0] router_001_src_data;                                                // router_001:src_data -> rsp_demux:sink_data
	wire          router_001_src_ready;                                               // rsp_demux:sink_ready -> router_001:src_ready
	wire    [1:0] router_001_src_channel;                                             // router_001:src_channel -> rsp_demux:sink_channel
	wire          router_001_src_startofpacket;                                       // router_001:src_startofpacket -> rsp_demux:sink_startofpacket
	wire          router_001_src_endofpacket;                                         // router_001:src_endofpacket -> rsp_demux:sink_endofpacket
	wire          axi_bridge_0_s0_agent_read_rp_valid;                                // axi_bridge_0_s0_agent:read_rp_valid -> router_002:sink_valid
	wire  [118:0] axi_bridge_0_s0_agent_read_rp_data;                                 // axi_bridge_0_s0_agent:read_rp_data -> router_002:sink_data
	wire          axi_bridge_0_s0_agent_read_rp_ready;                                // router_002:sink_ready -> axi_bridge_0_s0_agent:read_rp_ready
	wire          axi_bridge_0_s0_agent_read_rp_startofpacket;                        // axi_bridge_0_s0_agent:read_rp_startofpacket -> router_002:sink_startofpacket
	wire          axi_bridge_0_s0_agent_read_rp_endofpacket;                          // axi_bridge_0_s0_agent:read_rp_endofpacket -> router_002:sink_endofpacket
	wire          router_002_src_valid;                                               // router_002:src_valid -> rsp_demux_001:sink_valid
	wire  [118:0] router_002_src_data;                                                // router_002:src_data -> rsp_demux_001:sink_data
	wire          router_002_src_ready;                                               // rsp_demux_001:sink_ready -> router_002:src_ready
	wire    [1:0] router_002_src_channel;                                             // router_002:src_channel -> rsp_demux_001:sink_channel
	wire          router_002_src_startofpacket;                                       // router_002:src_startofpacket -> rsp_demux_001:sink_startofpacket
	wire          router_002_src_endofpacket;                                         // router_002:src_endofpacket -> rsp_demux_001:sink_endofpacket
	wire          router_src_valid;                                                   // router:src_valid -> master_0_master_limiter:cmd_sink_valid
	wire  [118:0] router_src_data;                                                    // router:src_data -> master_0_master_limiter:cmd_sink_data
	wire          router_src_ready;                                                   // master_0_master_limiter:cmd_sink_ready -> router:src_ready
	wire    [1:0] router_src_channel;                                                 // router:src_channel -> master_0_master_limiter:cmd_sink_channel
	wire          router_src_startofpacket;                                           // router:src_startofpacket -> master_0_master_limiter:cmd_sink_startofpacket
	wire          router_src_endofpacket;                                             // router:src_endofpacket -> master_0_master_limiter:cmd_sink_endofpacket
	wire  [118:0] master_0_master_limiter_cmd_src_data;                               // master_0_master_limiter:cmd_src_data -> cmd_demux:sink_data
	wire          master_0_master_limiter_cmd_src_ready;                              // cmd_demux:sink_ready -> master_0_master_limiter:cmd_src_ready
	wire    [1:0] master_0_master_limiter_cmd_src_channel;                            // master_0_master_limiter:cmd_src_channel -> cmd_demux:sink_channel
	wire          master_0_master_limiter_cmd_src_startofpacket;                      // master_0_master_limiter:cmd_src_startofpacket -> cmd_demux:sink_startofpacket
	wire          master_0_master_limiter_cmd_src_endofpacket;                        // master_0_master_limiter:cmd_src_endofpacket -> cmd_demux:sink_endofpacket
	wire          rsp_mux_src_valid;                                                  // rsp_mux:src_valid -> master_0_master_limiter:rsp_sink_valid
	wire  [118:0] rsp_mux_src_data;                                                   // rsp_mux:src_data -> master_0_master_limiter:rsp_sink_data
	wire          rsp_mux_src_ready;                                                  // master_0_master_limiter:rsp_sink_ready -> rsp_mux:src_ready
	wire    [1:0] rsp_mux_src_channel;                                                // rsp_mux:src_channel -> master_0_master_limiter:rsp_sink_channel
	wire          rsp_mux_src_startofpacket;                                          // rsp_mux:src_startofpacket -> master_0_master_limiter:rsp_sink_startofpacket
	wire          rsp_mux_src_endofpacket;                                            // rsp_mux:src_endofpacket -> master_0_master_limiter:rsp_sink_endofpacket
	wire          master_0_master_limiter_rsp_src_valid;                              // master_0_master_limiter:rsp_src_valid -> master_0_master_agent:rp_valid
	wire  [118:0] master_0_master_limiter_rsp_src_data;                               // master_0_master_limiter:rsp_src_data -> master_0_master_agent:rp_data
	wire          master_0_master_limiter_rsp_src_ready;                              // master_0_master_agent:rp_ready -> master_0_master_limiter:rsp_src_ready
	wire    [1:0] master_0_master_limiter_rsp_src_channel;                            // master_0_master_limiter:rsp_src_channel -> master_0_master_agent:rp_channel
	wire          master_0_master_limiter_rsp_src_startofpacket;                      // master_0_master_limiter:rsp_src_startofpacket -> master_0_master_agent:rp_startofpacket
	wire          master_0_master_limiter_rsp_src_endofpacket;                        // master_0_master_limiter:rsp_src_endofpacket -> master_0_master_agent:rp_endofpacket
	wire          cmd_demux_src0_valid;                                               // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [118:0] cmd_demux_src0_data;                                                // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire          cmd_demux_src0_ready;                                               // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire    [1:0] cmd_demux_src0_channel;                                             // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire          cmd_demux_src0_startofpacket;                                       // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire          cmd_demux_src0_endofpacket;                                         // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire          cmd_demux_src1_valid;                                               // cmd_demux:src1_valid -> cmd_mux_001:sink0_valid
	wire  [118:0] cmd_demux_src1_data;                                                // cmd_demux:src1_data -> cmd_mux_001:sink0_data
	wire          cmd_demux_src1_ready;                                               // cmd_mux_001:sink0_ready -> cmd_demux:src1_ready
	wire    [1:0] cmd_demux_src1_channel;                                             // cmd_demux:src1_channel -> cmd_mux_001:sink0_channel
	wire          cmd_demux_src1_startofpacket;                                       // cmd_demux:src1_startofpacket -> cmd_mux_001:sink0_startofpacket
	wire          cmd_demux_src1_endofpacket;                                         // cmd_demux:src1_endofpacket -> cmd_mux_001:sink0_endofpacket
	wire          rsp_demux_src0_valid;                                               // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [118:0] rsp_demux_src0_data;                                                // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire          rsp_demux_src0_ready;                                               // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire    [1:0] rsp_demux_src0_channel;                                             // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire          rsp_demux_src0_startofpacket;                                       // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire          rsp_demux_src0_endofpacket;                                         // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire          rsp_demux_001_src0_valid;                                           // rsp_demux_001:src0_valid -> rsp_mux:sink1_valid
	wire  [118:0] rsp_demux_001_src0_data;                                            // rsp_demux_001:src0_data -> rsp_mux:sink1_data
	wire          rsp_demux_001_src0_ready;                                           // rsp_mux:sink1_ready -> rsp_demux_001:src0_ready
	wire    [1:0] rsp_demux_001_src0_channel;                                         // rsp_demux_001:src0_channel -> rsp_mux:sink1_channel
	wire          rsp_demux_001_src0_startofpacket;                                   // rsp_demux_001:src0_startofpacket -> rsp_mux:sink1_startofpacket
	wire          rsp_demux_001_src0_endofpacket;                                     // rsp_demux_001:src0_endofpacket -> rsp_mux:sink1_endofpacket
	wire    [1:0] master_0_master_limiter_cmd_valid_data;                             // master_0_master_limiter:cmd_src_valid -> cmd_demux:sink_valid

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) master_0_master_translator (
		.clk                    (clk_0_clk_clk),                                                      //                       clk.clk
		.reset                  (axi_bridge_0_clk_reset_reset_bridge_in_reset_reset),                 //                     reset.reset
		.uav_address            (master_0_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (master_0_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (master_0_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (master_0_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (master_0_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (master_0_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (master_0_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (master_0_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (master_0_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (master_0_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (master_0_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (master_0_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (master_0_master_waitrequest),                                        //                          .waitrequest
		.av_byteenable          (master_0_master_byteenable),                                         //                          .byteenable
		.av_read                (master_0_master_read),                                               //                          .read
		.av_readdata            (master_0_master_readdata),                                           //                          .readdata
		.av_readdatavalid       (master_0_master_readdatavalid),                                      //                          .readdatavalid
		.av_write               (master_0_master_write),                                              //                          .write
		.av_writedata           (master_0_master_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                               //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                               //               (terminated)
		.av_begintransfer       (1'b0),                                                               //               (terminated)
		.av_chipselect          (1'b0),                                                               //               (terminated)
		.av_lock                (1'b0),                                                               //               (terminated)
		.av_debugaccess         (1'b0),                                                               //               (terminated)
		.uav_clken              (),                                                                   //               (terminated)
		.av_clken               (1'b1),                                                               //               (terminated)
		.uav_response           (2'b00),                                                              //               (terminated)
		.av_response            (),                                                                   //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                               //               (terminated)
		.av_writeresponsevalid  ()                                                                    //               (terminated)
	);

	altera_merlin_axi_translator #(
		.USE_S0_AWID                       (1),
		.USE_S0_AWREGION                   (1),
		.USE_M0_AWREGION                   (1),
		.USE_S0_AWLEN                      (1),
		.USE_S0_AWSIZE                     (1),
		.USE_S0_AWBURST                    (1),
		.USE_S0_AWLOCK                     (1),
		.USE_M0_AWLOCK                     (1),
		.USE_S0_AWCACHE                    (1),
		.USE_M0_AWCACHE                    (1),
		.USE_M0_AWPROT                     (1),
		.USE_S0_AWQOS                      (1),
		.USE_M0_AWQOS                      (1),
		.USE_S0_WSTRB                      (1),
		.USE_M0_WLAST                      (1),
		.USE_S0_BID                        (1),
		.USE_S0_BRESP                      (1),
		.USE_M0_BRESP                      (1),
		.USE_S0_ARID                       (1),
		.USE_S0_ARREGION                   (1),
		.USE_M0_ARREGION                   (1),
		.USE_S0_ARLEN                      (1),
		.USE_S0_ARSIZE                     (1),
		.USE_S0_ARBURST                    (1),
		.USE_S0_ARLOCK                     (1),
		.USE_M0_ARLOCK                     (1),
		.USE_M0_ARCACHE                    (1),
		.USE_M0_ARQOS                      (1),
		.USE_M0_ARPROT                     (1),
		.USE_S0_ARCACHE                    (1),
		.USE_S0_ARQOS                      (1),
		.USE_S0_RID                        (1),
		.USE_S0_RRESP                      (1),
		.USE_M0_RRESP                      (1),
		.USE_S0_RLAST                      (1),
		.M0_ID_WIDTH                       (8),
		.DATA_WIDTH                        (32),
		.S0_ID_WIDTH                       (1),
		.M0_ADDR_WIDTH                     (32),
		.S0_WRITE_ADDR_USER_WIDTH          (1),
		.S0_READ_ADDR_USER_WIDTH           (1),
		.M0_WRITE_ADDR_USER_WIDTH          (1),
		.M0_READ_ADDR_USER_WIDTH           (1),
		.S0_WRITE_DATA_USER_WIDTH          (1),
		.S0_WRITE_RESPONSE_DATA_USER_WIDTH (1),
		.S0_READ_DATA_USER_WIDTH           (1),
		.M0_WRITE_DATA_USER_WIDTH          (1),
		.M0_WRITE_RESPONSE_DATA_USER_WIDTH (1),
		.M0_READ_DATA_USER_WIDTH           (1),
		.S0_ADDR_WIDTH                     (32),
		.USE_S0_AWUSER                     (1),
		.USE_S0_ARUSER                     (1),
		.USE_S0_WUSER                      (1),
		.USE_S0_RUSER                      (1),
		.USE_S0_BUSER                      (1),
		.USE_M0_AWUSER                     (0),
		.USE_M0_ARUSER                     (0),
		.USE_M0_WUSER                      (0),
		.USE_M0_RUSER                      (0),
		.USE_M0_BUSER                      (0),
		.M0_AXI_VERSION                    ("AXI4"),
		.M0_BURST_LENGTH_WIDTH             (8),
		.S0_BURST_LENGTH_WIDTH             (8),
		.M0_LOCK_WIDTH                     (1),
		.S0_LOCK_WIDTH                     (1),
		.S0_AXI_VERSION                    ("AXI4")
	) axi_bridge_0_s0_translator (
		.aclk        (clk_0_clk_clk),                                       //       clk.clk
		.aresetn     (~axi_bridge_0_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset_n
		.m0_awid     (axi_bridge_0_s0_awid),                                //        m0.awid
		.m0_awaddr   (axi_bridge_0_s0_awaddr),                              //          .awaddr
		.m0_awlen    (axi_bridge_0_s0_awlen),                               //          .awlen
		.m0_awsize   (axi_bridge_0_s0_awsize),                              //          .awsize
		.m0_awburst  (axi_bridge_0_s0_awburst),                             //          .awburst
		.m0_awlock   (axi_bridge_0_s0_awlock),                              //          .awlock
		.m0_awcache  (axi_bridge_0_s0_awcache),                             //          .awcache
		.m0_awprot   (axi_bridge_0_s0_awprot),                              //          .awprot
		.m0_awqos    (axi_bridge_0_s0_awqos),                               //          .awqos
		.m0_awregion (axi_bridge_0_s0_awregion),                            //          .awregion
		.m0_awvalid  (axi_bridge_0_s0_awvalid),                             //          .awvalid
		.m0_awready  (axi_bridge_0_s0_awready),                             //          .awready
		.m0_wdata    (axi_bridge_0_s0_wdata),                               //          .wdata
		.m0_wstrb    (axi_bridge_0_s0_wstrb),                               //          .wstrb
		.m0_wlast    (axi_bridge_0_s0_wlast),                               //          .wlast
		.m0_wvalid   (axi_bridge_0_s0_wvalid),                              //          .wvalid
		.m0_wready   (axi_bridge_0_s0_wready),                              //          .wready
		.m0_bid      (axi_bridge_0_s0_bid),                                 //          .bid
		.m0_bresp    (axi_bridge_0_s0_bresp),                               //          .bresp
		.m0_bvalid   (axi_bridge_0_s0_bvalid),                              //          .bvalid
		.m0_bready   (axi_bridge_0_s0_bready),                              //          .bready
		.m0_arid     (axi_bridge_0_s0_arid),                                //          .arid
		.m0_araddr   (axi_bridge_0_s0_araddr),                              //          .araddr
		.m0_arlen    (axi_bridge_0_s0_arlen),                               //          .arlen
		.m0_arsize   (axi_bridge_0_s0_arsize),                              //          .arsize
		.m0_arburst  (axi_bridge_0_s0_arburst),                             //          .arburst
		.m0_arlock   (axi_bridge_0_s0_arlock),                              //          .arlock
		.m0_arcache  (axi_bridge_0_s0_arcache),                             //          .arcache
		.m0_arprot   (axi_bridge_0_s0_arprot),                              //          .arprot
		.m0_arqos    (axi_bridge_0_s0_arqos),                               //          .arqos
		.m0_arregion (axi_bridge_0_s0_arregion),                            //          .arregion
		.m0_arvalid  (axi_bridge_0_s0_arvalid),                             //          .arvalid
		.m0_arready  (axi_bridge_0_s0_arready),                             //          .arready
		.m0_rid      (axi_bridge_0_s0_rid),                                 //          .rid
		.m0_rdata    (axi_bridge_0_s0_rdata),                               //          .rdata
		.m0_rresp    (axi_bridge_0_s0_rresp),                               //          .rresp
		.m0_rlast    (axi_bridge_0_s0_rlast),                               //          .rlast
		.m0_rvalid   (axi_bridge_0_s0_rvalid),                              //          .rvalid
		.m0_rready   (axi_bridge_0_s0_rready),                              //          .rready
		.s0_awid     (axi_bridge_0_s0_agent_altera_axi_master_awid),        //        s0.awid
		.s0_awaddr   (axi_bridge_0_s0_agent_altera_axi_master_awaddr),      //          .awaddr
		.s0_awlen    (axi_bridge_0_s0_agent_altera_axi_master_awlen),       //          .awlen
		.s0_awsize   (axi_bridge_0_s0_agent_altera_axi_master_awsize),      //          .awsize
		.s0_awburst  (axi_bridge_0_s0_agent_altera_axi_master_awburst),     //          .awburst
		.s0_awlock   (axi_bridge_0_s0_agent_altera_axi_master_awlock),      //          .awlock
		.s0_awcache  (axi_bridge_0_s0_agent_altera_axi_master_awcache),     //          .awcache
		.s0_awprot   (axi_bridge_0_s0_agent_altera_axi_master_awprot),      //          .awprot
		.s0_awuser   (axi_bridge_0_s0_agent_altera_axi_master_awuser),      //          .awuser
		.s0_awqos    (axi_bridge_0_s0_agent_altera_axi_master_awqos),       //          .awqos
		.s0_awregion (axi_bridge_0_s0_agent_altera_axi_master_awregion),    //          .awregion
		.s0_awvalid  (axi_bridge_0_s0_agent_altera_axi_master_awvalid),     //          .awvalid
		.s0_awready  (axi_bridge_0_s0_agent_altera_axi_master_awready),     //          .awready
		.s0_wdata    (axi_bridge_0_s0_agent_altera_axi_master_wdata),       //          .wdata
		.s0_wstrb    (axi_bridge_0_s0_agent_altera_axi_master_wstrb),       //          .wstrb
		.s0_wlast    (axi_bridge_0_s0_agent_altera_axi_master_wlast),       //          .wlast
		.s0_wvalid   (axi_bridge_0_s0_agent_altera_axi_master_wvalid),      //          .wvalid
		.s0_wuser    (axi_bridge_0_s0_agent_altera_axi_master_wuser),       //          .wuser
		.s0_wready   (axi_bridge_0_s0_agent_altera_axi_master_wready),      //          .wready
		.s0_bid      (axi_bridge_0_s0_agent_altera_axi_master_bid),         //          .bid
		.s0_bresp    (axi_bridge_0_s0_agent_altera_axi_master_bresp),       //          .bresp
		.s0_buser    (axi_bridge_0_s0_agent_altera_axi_master_buser),       //          .buser
		.s0_bvalid   (axi_bridge_0_s0_agent_altera_axi_master_bvalid),      //          .bvalid
		.s0_bready   (axi_bridge_0_s0_agent_altera_axi_master_bready),      //          .bready
		.s0_arid     (axi_bridge_0_s0_agent_altera_axi_master_arid),        //          .arid
		.s0_araddr   (axi_bridge_0_s0_agent_altera_axi_master_araddr),      //          .araddr
		.s0_arlen    (axi_bridge_0_s0_agent_altera_axi_master_arlen),       //          .arlen
		.s0_arsize   (axi_bridge_0_s0_agent_altera_axi_master_arsize),      //          .arsize
		.s0_arburst  (axi_bridge_0_s0_agent_altera_axi_master_arburst),     //          .arburst
		.s0_arlock   (axi_bridge_0_s0_agent_altera_axi_master_arlock),      //          .arlock
		.s0_arcache  (axi_bridge_0_s0_agent_altera_axi_master_arcache),     //          .arcache
		.s0_arprot   (axi_bridge_0_s0_agent_altera_axi_master_arprot),      //          .arprot
		.s0_aruser   (axi_bridge_0_s0_agent_altera_axi_master_aruser),      //          .aruser
		.s0_arqos    (axi_bridge_0_s0_agent_altera_axi_master_arqos),       //          .arqos
		.s0_arregion (axi_bridge_0_s0_agent_altera_axi_master_arregion),    //          .arregion
		.s0_arvalid  (axi_bridge_0_s0_agent_altera_axi_master_arvalid),     //          .arvalid
		.s0_arready  (axi_bridge_0_s0_agent_altera_axi_master_arready),     //          .arready
		.s0_rid      (axi_bridge_0_s0_agent_altera_axi_master_rid),         //          .rid
		.s0_rdata    (axi_bridge_0_s0_agent_altera_axi_master_rdata),       //          .rdata
		.s0_rresp    (axi_bridge_0_s0_agent_altera_axi_master_rresp),       //          .rresp
		.s0_rlast    (axi_bridge_0_s0_agent_altera_axi_master_rlast),       //          .rlast
		.s0_rvalid   (axi_bridge_0_s0_agent_altera_axi_master_rvalid),      //          .rvalid
		.s0_rready   (axi_bridge_0_s0_agent_altera_axi_master_rready),      //          .rready
		.s0_ruser    (axi_bridge_0_s0_agent_altera_axi_master_ruser),       //          .ruser
		.m0_awuser   (),                                                    // (terminated)
		.m0_wuser    (),                                                    // (terminated)
		.m0_buser    (1'b0),                                                // (terminated)
		.m0_aruser   (),                                                    // (terminated)
		.m0_ruser    (1'b0),                                                // (terminated)
		.s0_wid      (1'b0),                                                // (terminated)
		.m0_wid      ()                                                     // (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (118),
		.PKT_ORI_BURST_SIZE_L      (116),
		.PKT_RESPONSE_STATUS_H     (115),
		.PKT_RESPONSE_STATUS_L     (114),
		.PKT_QOS_H                 (103),
		.PKT_QOS_L                 (100),
		.PKT_DATA_SIDEBAND_H       (98),
		.PKT_DATA_SIDEBAND_L       (98),
		.PKT_ADDR_SIDEBAND_H       (97),
		.PKT_ADDR_SIDEBAND_L       (97),
		.PKT_BURST_TYPE_H          (96),
		.PKT_BURST_TYPE_L          (95),
		.PKT_CACHE_H               (113),
		.PKT_CACHE_L               (110),
		.PKT_THREAD_ID_H           (106),
		.PKT_THREAD_ID_L           (106),
		.PKT_BURST_SIZE_H          (94),
		.PKT_BURST_SIZE_L          (92),
		.PKT_TRANS_EXCLUSIVE       (73),
		.PKT_TRANS_LOCK            (72),
		.PKT_BEGIN_BURST           (99),
		.PKT_PROTECTION_H          (109),
		.PKT_PROTECTION_L          (107),
		.PKT_BURSTWRAP_H           (91),
		.PKT_BURSTWRAP_L           (85),
		.PKT_BYTE_CNT_H            (84),
		.PKT_BYTE_CNT_L            (74),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (104),
		.PKT_SRC_ID_L              (104),
		.PKT_DEST_ID_H             (105),
		.PKT_DEST_ID_L             (105),
		.ST_DATA_W                 (119),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (3),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (127),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) master_0_master_agent (
		.clk                   (clk_0_clk_clk),                                                      //       clk.clk
		.reset                 (axi_bridge_0_clk_reset_reset_bridge_in_reset_reset),                 // clk_reset.reset
		.av_address            (master_0_master_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (master_0_master_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (master_0_master_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (master_0_master_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (master_0_master_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (master_0_master_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (master_0_master_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (master_0_master_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (master_0_master_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (master_0_master_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (master_0_master_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (master_0_master_agent_cp_valid),                                     //        cp.valid
		.cp_data               (master_0_master_agent_cp_data),                                      //          .data
		.cp_startofpacket      (master_0_master_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (master_0_master_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (master_0_master_agent_cp_ready),                                     //          .ready
		.rp_valid              (master_0_master_limiter_rsp_src_valid),                              //        rp.valid
		.rp_data               (master_0_master_limiter_rsp_src_data),                               //          .data
		.rp_channel            (master_0_master_limiter_rsp_src_channel),                            //          .channel
		.rp_startofpacket      (master_0_master_limiter_rsp_src_startofpacket),                      //          .startofpacket
		.rp_endofpacket        (master_0_master_limiter_rsp_src_endofpacket),                        //          .endofpacket
		.rp_ready              (master_0_master_limiter_rsp_src_ready),                              //          .ready
		.av_response           (),                                                                   // (terminated)
		.av_writeresponsevalid ()                                                                    // (terminated)
	);

	altera_merlin_axi_slave_ni #(
		.PKT_QOS_H                   (103),
		.PKT_QOS_L                   (100),
		.PKT_THREAD_ID_H             (106),
		.PKT_THREAD_ID_L             (106),
		.PKT_RESPONSE_STATUS_H       (115),
		.PKT_RESPONSE_STATUS_L       (114),
		.PKT_BEGIN_BURST             (99),
		.PKT_CACHE_H                 (113),
		.PKT_CACHE_L                 (110),
		.PKT_DATA_SIDEBAND_H         (98),
		.PKT_DATA_SIDEBAND_L         (98),
		.PKT_ADDR_SIDEBAND_H         (97),
		.PKT_ADDR_SIDEBAND_L         (97),
		.PKT_BURST_TYPE_H            (96),
		.PKT_BURST_TYPE_L            (95),
		.PKT_PROTECTION_H            (109),
		.PKT_PROTECTION_L            (107),
		.PKT_BURST_SIZE_H            (94),
		.PKT_BURST_SIZE_L            (92),
		.PKT_BURSTWRAP_H             (91),
		.PKT_BURSTWRAP_L             (85),
		.PKT_BYTE_CNT_H              (84),
		.PKT_BYTE_CNT_L              (74),
		.PKT_ADDR_H                  (67),
		.PKT_ADDR_L                  (36),
		.PKT_TRANS_EXCLUSIVE         (73),
		.PKT_TRANS_LOCK              (72),
		.PKT_TRANS_COMPRESSED_READ   (68),
		.PKT_TRANS_POSTED            (69),
		.PKT_TRANS_WRITE             (70),
		.PKT_TRANS_READ              (71),
		.PKT_DATA_H                  (31),
		.PKT_DATA_L                  (0),
		.PKT_BYTEEN_H                (35),
		.PKT_BYTEEN_L                (32),
		.PKT_SRC_ID_H                (104),
		.PKT_SRC_ID_L                (104),
		.PKT_DEST_ID_H               (105),
		.PKT_DEST_ID_L               (105),
		.PKT_ORI_BURST_SIZE_L        (116),
		.PKT_ORI_BURST_SIZE_H        (118),
		.ADDR_USER_WIDTH             (1),
		.DATA_USER_WIDTH             (1),
		.ST_DATA_W                   (119),
		.ADDR_WIDTH                  (32),
		.RDATA_WIDTH                 (32),
		.WDATA_WIDTH                 (32),
		.ST_CHANNEL_W                (2),
		.AXI_SLAVE_ID_W              (1),
		.PASS_ID_TO_SLAVE            (1),
		.AXI_VERSION                 ("AXI4"),
		.WRITE_ACCEPTANCE_CAPABILITY (16),
		.READ_ACCEPTANCE_CAPABILITY  (16)
	) axi_bridge_0_s0_agent (
		.aclk                   (clk_0_clk_clk),                                       //        clock_sink.clk
		.aresetn                (~axi_bridge_0_clk_reset_reset_bridge_in_reset_reset), //        reset_sink.reset_n
		.read_cp_valid          (cmd_mux_001_src_valid),                               //           read_cp.valid
		.read_cp_ready          (cmd_mux_001_src_ready),                               //                  .ready
		.read_cp_data           (cmd_mux_001_src_data),                                //                  .data
		.read_cp_channel        (cmd_mux_001_src_channel),                             //                  .channel
		.read_cp_startofpacket  (cmd_mux_001_src_startofpacket),                       //                  .startofpacket
		.read_cp_endofpacket    (cmd_mux_001_src_endofpacket),                         //                  .endofpacket
		.write_cp_ready         (cmd_mux_src_ready),                                   //          write_cp.ready
		.write_cp_valid         (cmd_mux_src_valid),                                   //                  .valid
		.write_cp_data          (cmd_mux_src_data),                                    //                  .data
		.write_cp_channel       (cmd_mux_src_channel),                                 //                  .channel
		.write_cp_startofpacket (cmd_mux_src_startofpacket),                           //                  .startofpacket
		.write_cp_endofpacket   (cmd_mux_src_endofpacket),                             //                  .endofpacket
		.read_rp_ready          (axi_bridge_0_s0_agent_read_rp_ready),                 //           read_rp.ready
		.read_rp_valid          (axi_bridge_0_s0_agent_read_rp_valid),                 //                  .valid
		.read_rp_data           (axi_bridge_0_s0_agent_read_rp_data),                  //                  .data
		.read_rp_startofpacket  (axi_bridge_0_s0_agent_read_rp_startofpacket),         //                  .startofpacket
		.read_rp_endofpacket    (axi_bridge_0_s0_agent_read_rp_endofpacket),           //                  .endofpacket
		.write_rp_ready         (axi_bridge_0_s0_agent_write_rp_ready),                //          write_rp.ready
		.write_rp_valid         (axi_bridge_0_s0_agent_write_rp_valid),                //                  .valid
		.write_rp_data          (axi_bridge_0_s0_agent_write_rp_data),                 //                  .data
		.write_rp_startofpacket (axi_bridge_0_s0_agent_write_rp_startofpacket),        //                  .startofpacket
		.write_rp_endofpacket   (axi_bridge_0_s0_agent_write_rp_endofpacket),          //                  .endofpacket
		.awid                   (axi_bridge_0_s0_agent_altera_axi_master_awid),        // altera_axi_master.awid
		.awaddr                 (axi_bridge_0_s0_agent_altera_axi_master_awaddr),      //                  .awaddr
		.awlen                  (axi_bridge_0_s0_agent_altera_axi_master_awlen),       //                  .awlen
		.awsize                 (axi_bridge_0_s0_agent_altera_axi_master_awsize),      //                  .awsize
		.awburst                (axi_bridge_0_s0_agent_altera_axi_master_awburst),     //                  .awburst
		.awlock                 (axi_bridge_0_s0_agent_altera_axi_master_awlock),      //                  .awlock
		.awcache                (axi_bridge_0_s0_agent_altera_axi_master_awcache),     //                  .awcache
		.awprot                 (axi_bridge_0_s0_agent_altera_axi_master_awprot),      //                  .awprot
		.awuser                 (axi_bridge_0_s0_agent_altera_axi_master_awuser),      //                  .awuser
		.awvalid                (axi_bridge_0_s0_agent_altera_axi_master_awvalid),     //                  .awvalid
		.awready                (axi_bridge_0_s0_agent_altera_axi_master_awready),     //                  .awready
		.wdata                  (axi_bridge_0_s0_agent_altera_axi_master_wdata),       //                  .wdata
		.wstrb                  (axi_bridge_0_s0_agent_altera_axi_master_wstrb),       //                  .wstrb
		.wlast                  (axi_bridge_0_s0_agent_altera_axi_master_wlast),       //                  .wlast
		.wvalid                 (axi_bridge_0_s0_agent_altera_axi_master_wvalid),      //                  .wvalid
		.wready                 (axi_bridge_0_s0_agent_altera_axi_master_wready),      //                  .wready
		.bid                    (axi_bridge_0_s0_agent_altera_axi_master_bid),         //                  .bid
		.bresp                  (axi_bridge_0_s0_agent_altera_axi_master_bresp),       //                  .bresp
		.bvalid                 (axi_bridge_0_s0_agent_altera_axi_master_bvalid),      //                  .bvalid
		.bready                 (axi_bridge_0_s0_agent_altera_axi_master_bready),      //                  .bready
		.arid                   (axi_bridge_0_s0_agent_altera_axi_master_arid),        //                  .arid
		.araddr                 (axi_bridge_0_s0_agent_altera_axi_master_araddr),      //                  .araddr
		.arlen                  (axi_bridge_0_s0_agent_altera_axi_master_arlen),       //                  .arlen
		.arsize                 (axi_bridge_0_s0_agent_altera_axi_master_arsize),      //                  .arsize
		.arburst                (axi_bridge_0_s0_agent_altera_axi_master_arburst),     //                  .arburst
		.arlock                 (axi_bridge_0_s0_agent_altera_axi_master_arlock),      //                  .arlock
		.arcache                (axi_bridge_0_s0_agent_altera_axi_master_arcache),     //                  .arcache
		.arprot                 (axi_bridge_0_s0_agent_altera_axi_master_arprot),      //                  .arprot
		.aruser                 (axi_bridge_0_s0_agent_altera_axi_master_aruser),      //                  .aruser
		.arvalid                (axi_bridge_0_s0_agent_altera_axi_master_arvalid),     //                  .arvalid
		.arready                (axi_bridge_0_s0_agent_altera_axi_master_arready),     //                  .arready
		.rid                    (axi_bridge_0_s0_agent_altera_axi_master_rid),         //                  .rid
		.rdata                  (axi_bridge_0_s0_agent_altera_axi_master_rdata),       //                  .rdata
		.rresp                  (axi_bridge_0_s0_agent_altera_axi_master_rresp),       //                  .rresp
		.rlast                  (axi_bridge_0_s0_agent_altera_axi_master_rlast),       //                  .rlast
		.rvalid                 (axi_bridge_0_s0_agent_altera_axi_master_rvalid),      //                  .rvalid
		.rready                 (axi_bridge_0_s0_agent_altera_axi_master_rready),      //                  .rready
		.wuser                  (axi_bridge_0_s0_agent_altera_axi_master_wuser),       //                  .wuser
		.awqos                  (axi_bridge_0_s0_agent_altera_axi_master_awqos),       //                  .awqos
		.awregion               (axi_bridge_0_s0_agent_altera_axi_master_awregion),    //                  .awregion
		.ruser                  (axi_bridge_0_s0_agent_altera_axi_master_ruser),       //                  .ruser
		.buser                  (axi_bridge_0_s0_agent_altera_axi_master_buser),       //                  .buser
		.arqos                  (axi_bridge_0_s0_agent_altera_axi_master_arqos),       //                  .arqos
		.arregion               (axi_bridge_0_s0_agent_altera_axi_master_arregion)     //                  .arregion
	);

	jtag_axi_sys_mm_interconnect_0_router router (
		.sink_ready         (master_0_master_agent_cp_ready),                     //      sink.ready
		.sink_valid         (master_0_master_agent_cp_valid),                     //          .valid
		.sink_data          (master_0_master_agent_cp_data),                      //          .data
		.sink_startofpacket (master_0_master_agent_cp_startofpacket),             //          .startofpacket
		.sink_endofpacket   (master_0_master_agent_cp_endofpacket),               //          .endofpacket
		.clk                (clk_0_clk_clk),                                      //       clk.clk
		.reset              (axi_bridge_0_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                                   //       src.ready
		.src_valid          (router_src_valid),                                   //          .valid
		.src_data           (router_src_data),                                    //          .data
		.src_channel        (router_src_channel),                                 //          .channel
		.src_startofpacket  (router_src_startofpacket),                           //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                              //          .endofpacket
	);

	jtag_axi_sys_mm_interconnect_0_router_001 router_001 (
		.sink_ready         (axi_bridge_0_s0_agent_write_rp_ready),               //      sink.ready
		.sink_valid         (axi_bridge_0_s0_agent_write_rp_valid),               //          .valid
		.sink_data          (axi_bridge_0_s0_agent_write_rp_data),                //          .data
		.sink_startofpacket (axi_bridge_0_s0_agent_write_rp_startofpacket),       //          .startofpacket
		.sink_endofpacket   (axi_bridge_0_s0_agent_write_rp_endofpacket),         //          .endofpacket
		.clk                (clk_0_clk_clk),                                      //       clk.clk
		.reset              (axi_bridge_0_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                               //       src.ready
		.src_valid          (router_001_src_valid),                               //          .valid
		.src_data           (router_001_src_data),                                //          .data
		.src_channel        (router_001_src_channel),                             //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                       //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                          //          .endofpacket
	);

	jtag_axi_sys_mm_interconnect_0_router_001 router_002 (
		.sink_ready         (axi_bridge_0_s0_agent_read_rp_ready),                //      sink.ready
		.sink_valid         (axi_bridge_0_s0_agent_read_rp_valid),                //          .valid
		.sink_data          (axi_bridge_0_s0_agent_read_rp_data),                 //          .data
		.sink_startofpacket (axi_bridge_0_s0_agent_read_rp_startofpacket),        //          .startofpacket
		.sink_endofpacket   (axi_bridge_0_s0_agent_read_rp_endofpacket),          //          .endofpacket
		.clk                (clk_0_clk_clk),                                      //       clk.clk
		.reset              (axi_bridge_0_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_002_src_ready),                               //       src.ready
		.src_valid          (router_002_src_valid),                               //          .valid
		.src_data           (router_002_src_data),                                //          .data
		.src_channel        (router_002_src_channel),                             //          .channel
		.src_startofpacket  (router_002_src_startofpacket),                       //          .startofpacket
		.src_endofpacket    (router_002_src_endofpacket)                          //          .endofpacket
	);

	altera_merlin_traffic_limiter #(
		.PKT_DEST_ID_H             (105),
		.PKT_DEST_ID_L             (105),
		.PKT_SRC_ID_H              (104),
		.PKT_SRC_ID_L              (104),
		.PKT_BYTE_CNT_H            (84),
		.PKT_BYTE_CNT_L            (74),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.MAX_OUTSTANDING_RESPONSES (16),
		.PIPELINED                 (0),
		.ST_DATA_W                 (119),
		.ST_CHANNEL_W              (2),
		.VALID_WIDTH               (2),
		.ENFORCE_ORDER             (1),
		.PREVENT_HAZARDS           (1),
		.SUPPORTS_POSTED_WRITES    (1),
		.SUPPORTS_NONPOSTED_WRITES (0),
		.REORDER                   (0)
	) master_0_master_limiter (
		.clk                    (clk_0_clk_clk),                                      //       clk.clk
		.reset                  (axi_bridge_0_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.cmd_sink_ready         (router_src_ready),                                   //  cmd_sink.ready
		.cmd_sink_valid         (router_src_valid),                                   //          .valid
		.cmd_sink_data          (router_src_data),                                    //          .data
		.cmd_sink_channel       (router_src_channel),                                 //          .channel
		.cmd_sink_startofpacket (router_src_startofpacket),                           //          .startofpacket
		.cmd_sink_endofpacket   (router_src_endofpacket),                             //          .endofpacket
		.cmd_src_ready          (master_0_master_limiter_cmd_src_ready),              //   cmd_src.ready
		.cmd_src_data           (master_0_master_limiter_cmd_src_data),               //          .data
		.cmd_src_channel        (master_0_master_limiter_cmd_src_channel),            //          .channel
		.cmd_src_startofpacket  (master_0_master_limiter_cmd_src_startofpacket),      //          .startofpacket
		.cmd_src_endofpacket    (master_0_master_limiter_cmd_src_endofpacket),        //          .endofpacket
		.rsp_sink_ready         (rsp_mux_src_ready),                                  //  rsp_sink.ready
		.rsp_sink_valid         (rsp_mux_src_valid),                                  //          .valid
		.rsp_sink_channel       (rsp_mux_src_channel),                                //          .channel
		.rsp_sink_data          (rsp_mux_src_data),                                   //          .data
		.rsp_sink_startofpacket (rsp_mux_src_startofpacket),                          //          .startofpacket
		.rsp_sink_endofpacket   (rsp_mux_src_endofpacket),                            //          .endofpacket
		.rsp_src_ready          (master_0_master_limiter_rsp_src_ready),              //   rsp_src.ready
		.rsp_src_valid          (master_0_master_limiter_rsp_src_valid),              //          .valid
		.rsp_src_data           (master_0_master_limiter_rsp_src_data),               //          .data
		.rsp_src_channel        (master_0_master_limiter_rsp_src_channel),            //          .channel
		.rsp_src_startofpacket  (master_0_master_limiter_rsp_src_startofpacket),      //          .startofpacket
		.rsp_src_endofpacket    (master_0_master_limiter_rsp_src_endofpacket),        //          .endofpacket
		.cmd_src_valid          (master_0_master_limiter_cmd_valid_data)              // cmd_valid.data
	);

	jtag_axi_sys_mm_interconnect_0_cmd_demux cmd_demux (
		.clk                (clk_0_clk_clk),                                      //        clk.clk
		.reset              (axi_bridge_0_clk_reset_reset_bridge_in_reset_reset), //  clk_reset.reset
		.sink_ready         (master_0_master_limiter_cmd_src_ready),              //       sink.ready
		.sink_channel       (master_0_master_limiter_cmd_src_channel),            //           .channel
		.sink_data          (master_0_master_limiter_cmd_src_data),               //           .data
		.sink_startofpacket (master_0_master_limiter_cmd_src_startofpacket),      //           .startofpacket
		.sink_endofpacket   (master_0_master_limiter_cmd_src_endofpacket),        //           .endofpacket
		.sink_valid         (master_0_master_limiter_cmd_valid_data),             // sink_valid.data
		.src0_ready         (cmd_demux_src0_ready),                               //       src0.ready
		.src0_valid         (cmd_demux_src0_valid),                               //           .valid
		.src0_data          (cmd_demux_src0_data),                                //           .data
		.src0_channel       (cmd_demux_src0_channel),                             //           .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                       //           .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket),                         //           .endofpacket
		.src1_ready         (cmd_demux_src1_ready),                               //       src1.ready
		.src1_valid         (cmd_demux_src1_valid),                               //           .valid
		.src1_data          (cmd_demux_src1_data),                                //           .data
		.src1_channel       (cmd_demux_src1_channel),                             //           .channel
		.src1_startofpacket (cmd_demux_src1_startofpacket),                       //           .startofpacket
		.src1_endofpacket   (cmd_demux_src1_endofpacket)                          //           .endofpacket
	);

	jtag_axi_sys_mm_interconnect_0_cmd_mux cmd_mux (
		.clk                 (clk_0_clk_clk),                                      //       clk.clk
		.reset               (axi_bridge_0_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                                  //       src.ready
		.src_valid           (cmd_mux_src_valid),                                  //          .valid
		.src_data            (cmd_mux_src_data),                                   //          .data
		.src_channel         (cmd_mux_src_channel),                                //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                          //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                            //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                               //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                               //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                             //          .channel
		.sink0_data          (cmd_demux_src0_data),                                //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                       //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket)                          //          .endofpacket
	);

	jtag_axi_sys_mm_interconnect_0_cmd_mux cmd_mux_001 (
		.clk                 (clk_0_clk_clk),                                      //       clk.clk
		.reset               (axi_bridge_0_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_001_src_ready),                              //       src.ready
		.src_valid           (cmd_mux_001_src_valid),                              //          .valid
		.src_data            (cmd_mux_001_src_data),                               //          .data
		.src_channel         (cmd_mux_001_src_channel),                            //          .channel
		.src_startofpacket   (cmd_mux_001_src_startofpacket),                      //          .startofpacket
		.src_endofpacket     (cmd_mux_001_src_endofpacket),                        //          .endofpacket
		.sink0_ready         (cmd_demux_src1_ready),                               //     sink0.ready
		.sink0_valid         (cmd_demux_src1_valid),                               //          .valid
		.sink0_channel       (cmd_demux_src1_channel),                             //          .channel
		.sink0_data          (cmd_demux_src1_data),                                //          .data
		.sink0_startofpacket (cmd_demux_src1_startofpacket),                       //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src1_endofpacket)                          //          .endofpacket
	);

	jtag_axi_sys_mm_interconnect_0_rsp_demux rsp_demux (
		.clk                (clk_0_clk_clk),                                      //       clk.clk
		.reset              (axi_bridge_0_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_001_src_ready),                               //      sink.ready
		.sink_channel       (router_001_src_channel),                             //          .channel
		.sink_data          (router_001_src_data),                                //          .data
		.sink_startofpacket (router_001_src_startofpacket),                       //          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                         //          .endofpacket
		.sink_valid         (router_001_src_valid),                               //          .valid
		.src0_ready         (rsp_demux_src0_ready),                               //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                               //          .valid
		.src0_data          (rsp_demux_src0_data),                                //          .data
		.src0_channel       (rsp_demux_src0_channel),                             //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                       //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                          //          .endofpacket
	);

	jtag_axi_sys_mm_interconnect_0_rsp_demux rsp_demux_001 (
		.clk                (clk_0_clk_clk),                                      //       clk.clk
		.reset              (axi_bridge_0_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_002_src_ready),                               //      sink.ready
		.sink_channel       (router_002_src_channel),                             //          .channel
		.sink_data          (router_002_src_data),                                //          .data
		.sink_startofpacket (router_002_src_startofpacket),                       //          .startofpacket
		.sink_endofpacket   (router_002_src_endofpacket),                         //          .endofpacket
		.sink_valid         (router_002_src_valid),                               //          .valid
		.src0_ready         (rsp_demux_001_src0_ready),                           //      src0.ready
		.src0_valid         (rsp_demux_001_src0_valid),                           //          .valid
		.src0_data          (rsp_demux_001_src0_data),                            //          .data
		.src0_channel       (rsp_demux_001_src0_channel),                         //          .channel
		.src0_startofpacket (rsp_demux_001_src0_startofpacket),                   //          .startofpacket
		.src0_endofpacket   (rsp_demux_001_src0_endofpacket)                      //          .endofpacket
	);

	jtag_axi_sys_mm_interconnect_0_rsp_mux rsp_mux (
		.clk                 (clk_0_clk_clk),                                      //       clk.clk
		.reset               (axi_bridge_0_clk_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                                  //       src.ready
		.src_valid           (rsp_mux_src_valid),                                  //          .valid
		.src_data            (rsp_mux_src_data),                                   //          .data
		.src_channel         (rsp_mux_src_channel),                                //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                          //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                            //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                               //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                               //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                             //          .channel
		.sink0_data          (rsp_demux_src0_data),                                //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                       //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket),                         //          .endofpacket
		.sink1_ready         (rsp_demux_001_src0_ready),                           //     sink1.ready
		.sink1_valid         (rsp_demux_001_src0_valid),                           //          .valid
		.sink1_channel       (rsp_demux_001_src0_channel),                         //          .channel
		.sink1_data          (rsp_demux_001_src0_data),                            //          .data
		.sink1_startofpacket (rsp_demux_001_src0_startofpacket),                   //          .startofpacket
		.sink1_endofpacket   (rsp_demux_001_src0_endofpacket)                      //          .endofpacket
	);

endmodule
